main/urls.py
from django.urls import path
from .views import (
    main, create_item, edit_item, delete_item, create_item_ajax,
    show_json, show_json_by_id, 
    show_xml, show_xml_by_id, 
    register, login_user, logout_user, create_item_flutter)

app_name = "main"

urlpatterns = [
    path('', main, name='main'),
    path('create-item', create_item, name='create_item'),
    path('create-item-ajax', create_item_ajax, name='create_item_ajax'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('delete-item/<int:id>', delete_item, name='delete_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-flutter/', create_item_flutter, name='create_book_flutter'),
]

tugas_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as main_urls
from authentication import urls as authentication_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include(main_urls)),
    path('auth/', include(authentication_urls)),
]

templates/base_html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {%endblock%}</title>
</head>
<body>
    {%block content%}
    {%endblock%}
</body>
</html>

templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    {% block head %} {% endblock head %}

</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/navbar.html
{% load static %}

<link rel="stylesheet" href="{% static 'main/css/main.css' %}">

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">{% include 'calendar_icon.html' %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% with app_name=request.resolver_match.app_name url_name=request.resolver_match.url_name %}
          <li class="nav-item">
            <a class="nav-link {% if app_name == 'main' and url_name == 'main' %}active custom_li{% endif %}" href="{% url 'main:main' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if app_name == 'main' and url_name == 'create_item' %}active custom_li{% endif %}" href="{% url 'main:create_item' %}">Add a Task</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</a>
          </li>
          {% endwith %}
        </ul>
        <a href="{% url 'main:logout' %}">
          <button type="button" class="btn btn-outline-primary">Logout</button>
        </a>
      </div>
    </div>
  </nav>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="page" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                      <label for="page" class="col-form-label">Deadline:</label>
                      <input type="datetime-local" class="form-control" id="deadline" name="deadline"></input>
                  </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
            </div>
        </div>
    </div>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
        // Assign addBook function to the click event of "Add Book" button
        document.getElementById("button_add").addEventListener("click", addItem);
    });

    function addItem() {
        fetch("{% url 'main:create_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(() => {
            document.getElementById("form").reset();

            var modal = document.getElementById("exampleModal");
            var modalInstance = bootstrap.Modal.getInstance(modal);
            modalInstance.hide();

            updateItems();
        }).catch(error => {
            console.error('Error adding item:', error);
        });
        return false;
    }
</script>