main/urls.py
from django.urls import path
from .views import (
    main, create_item, edit_item, delete_item, create_item_ajax,
    show_json, show_json_by_id, 
    show_xml, show_xml_by_id, 
    register, login_user, logout_user, create_item_flutter)

app_name = "main"

urlpatterns = [
    path('', main, name='main'),
    path('create-item', create_item, name='create_item'),
    path('create-item-ajax', create_item_ajax, name='create_item_ajax'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('delete-item/<int:id>', delete_item, name='delete_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-flutter/', create_item_flutter, name='create_book_flutter'),
]

tugas_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as main_urls
from authentication import urls as authentication_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include(main_urls)),
    path('auth/', include(authentication_urls)),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    deadline = models.DateTimeField()

main/forms.py
from django.forms import ModelForm, TextInput
from .models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = "__all__"
        exclude = ("user",)
        widgets = {
            'deadline':TextInput(attrs={'type':'datetime-local'}),
        }

main/views.py
import datetime, json
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse

from .models import Item
from .forms import ItemForm

@login_required(login_url='/login')
def main(request):
    user = request.user
    last_login = user.last_login
    items = Item.objects.filter(user=user)

    # Convert datetime fields in items queryset to formatted strings
    formatted_items = []
    for item in items:
        formatted_item = {
            'id': item.id,
            'name': item.name,
            'amount': item.amount,
            'description': item.description,
            'date_added': item.date_added.strftime("%B %d, %Y"),
            'deadline': item.deadline.strftime("%B %d, %Y, %I:%M %p"),
        }
        formatted_items.append(formatted_item)

    identifier = {
        "app_name": "Tugas Tracker",
        "name": user.username,
        "class": "A",
        "last_login": last_login.strftime("%B %d, %Y, %I:%M %p"),
    }

    # Encode the formatted items queryset to JSON
    items_json = json.dumps(formatted_items)
    items = items_json
    return render(request, "main_landingpage.html", {"identifier":identifier, "items":items})

@login_required(login_url='/login')
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return redirect('main:main')

    context = {'form': form}
    return render(request, "create_item.html", context)

@login_required(login_url='/login')
def edit_item(request, id):
    item = Item.objects.get(pk = id)

    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

@login_required(login_url='/login')
def delete_item(request, id):
    item = Item.objects.get(pk = id)
    item.delete()
    return HttpResponseRedirect(reverse('main:main'))

@csrf_exempt
def create_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        deadline = request.POST.get("deadline")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, deadline=deadline, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
            deadline = data["deadline"],
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/calendar_icon.html
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg fill="#000000" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 width="57px" height="55px" viewBox="0 0 610.398 610.398"
	 xml:space="preserve">
<g>
	<g>
		<path class="icon" d="M159.567,0h-15.329c-1.956,0-3.811,0.411-5.608,0.995c-8.979,2.912-15.616,12.498-15.616,23.997v10.552v27.009v14.052
			c0,2.611,0.435,5.078,1.066,7.44c2.702,10.146,10.653,17.552,20.158,17.552h15.329c11.724,0,21.224-11.188,21.224-24.992V62.553
			V35.544V24.992C180.791,11.188,171.291,0,159.567,0z"/>
		<path class="icon" d="M461.288,0h-15.329c-11.724,0-21.224,11.188-21.224,24.992v10.552v27.009v14.052c0,13.804,9.5,24.992,21.224,24.992
			h15.329c11.724,0,21.224-11.188,21.224-24.992V62.553V35.544V24.992C482.507,11.188,473.007,0,461.288,0z"/>
		<path class="icon" d="M539.586,62.553h-37.954v14.052c0,24.327-18.102,44.117-40.349,44.117h-15.329c-22.247,0-40.349-19.79-40.349-44.117
			V62.553H199.916v14.052c0,24.327-18.102,44.117-40.349,44.117h-15.329c-22.248,0-40.349-19.79-40.349-44.117V62.553H70.818
			c-21.066,0-38.15,16.017-38.15,35.764v476.318c0,19.784,17.083,35.764,38.15,35.764h468.763c21.085,0,38.149-15.984,38.149-35.764
			V98.322C577.735,78.575,560.671,62.553,539.586,62.553z M527.757,557.9l-446.502-0.172V173.717h446.502V557.9z"/>
		<path class="icon" d="M353.017,266.258h117.428c10.193,0,18.437-10.179,18.437-22.759s-8.248-22.759-18.437-22.759H353.017
			c-10.193,0-18.437,10.179-18.437,22.759C334.58,256.074,342.823,266.258,353.017,266.258z"/>
		<path class="icon" d="M353.017,348.467h117.428c10.193,0,18.437-10.179,18.437-22.759c0-12.579-8.248-22.758-18.437-22.758H353.017
			c-10.193,0-18.437,10.179-18.437,22.758C334.58,338.288,342.823,348.467,353.017,348.467z"/>
		<path class="icon" d="M353.017,430.676h117.428c10.193,0,18.437-10.18,18.437-22.759s-8.248-22.759-18.437-22.759H353.017
			c-10.193,0-18.437,10.18-18.437,22.759S342.823,430.676,353.017,430.676z"/>
		<path class="icon" d="M353.017,512.89h117.428c10.193,0,18.437-10.18,18.437-22.759c0-12.58-8.248-22.759-18.437-22.759H353.017
			c-10.193,0-18.437,10.179-18.437,22.759C334.58,502.71,342.823,512.89,353.017,512.89z"/>
		<path class="icon" d="M145.032,266.258H262.46c10.193,0,18.436-10.179,18.436-22.759s-8.248-22.759-18.436-22.759H145.032
			c-10.194,0-18.437,10.179-18.437,22.759C126.596,256.074,134.838,266.258,145.032,266.258z"/>
		<path class="icon" d="M145.032,348.467H262.46c10.193,0,18.436-10.179,18.436-22.759c0-12.579-8.248-22.758-18.436-22.758H145.032
			c-10.194,0-18.437,10.179-18.437,22.758C126.596,338.288,134.838,348.467,145.032,348.467z"/>
		<path class="icon" d="M145.032,430.676H262.46c10.193,0,18.436-10.18,18.436-22.759s-8.248-22.759-18.436-22.759H145.032
			c-10.194,0-18.437,10.18-18.437,22.759S134.838,430.676,145.032,430.676z"/>
		<path class="icon" d="M145.032,512.89H262.46c10.193,0,18.436-10.18,18.436-22.759c0-12.58-8.248-22.759-18.436-22.759H145.032
			c-10.194,0-18.437,10.179-18.437,22.759C126.596,502.71,134.838,512.89,145.032,512.89z"/>
	</g>
</g>
</svg>

main/templates/create_item.html
{% extends 'base_template.html' %}
{% block title %} Create an Item {% endblock title %}
{% block content %}
<h1>Add New Item</h1>


<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add Item" />
      </td>
    </tr>
  </table>
</form>

{% endblock content %}

main/templates/edit_item.html
{% extends 'base_template.html' %}
{% block title %} Edit Item {% endblock title %}
{% block content %}

<h1>Edit Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input class="btn btn-primary" type="submit" value="Edit Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base_template.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %} 

{% block content %}
<div class="login">
  <h1>Login</h1>

  <form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
        <td>Username:</td>
        <td>
          <input
            type="text"
            name="username"
            placeholder="Username"
            class="form-control"
          />
        </td>
      </tr>

      <tr>
        <td>Password:</td>
        <td>
          <input
            type="password"
            name="password"
            placeholder="Password"
            class="form-control"
          />
        </td>
      </tr>

      <tr>
        <td></td>
        <td><input class="btn btn-outline-primary" type="submit" value="Login" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} Don't have an account yet?
  <a href="{% url 'main:register' %}">Register Now</a>
</div>

{% endblock content %}

main/templates/main_landingpage.html
{% extends "base_template.html" %}

{% load static %}

{% block title %}
Tugas Tracker
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% endblock head %}

{%block content %}
<h2>App Name: {{identifier.app_name}}</h2>
<h3>Name: {{identifier.name}}</h3>
<h4>Class: {{identifier.class}}</h4>
<h5>Sesi terakhir login:{{identifier.last_login}}</h5>

<div class="card-box">
</div>

<script>
  async function getItems() {
    let url = "{% url 'main:show_json' %}"
    const res = await fetch(url)
    return await res.json()
  }

  async function updateItems(){
    let url = "{% url 'main:show_json' %}"
    const res = await fetch(url)
    document.querySelector(".card-box").innerHTML = await refreshItems()
  }
  
  async function refreshItems() {
    const items = await getItems();
    console.log(items)
    let htmlString = ""
    items.forEach((item) => {
      const deadlineDate = new Date(item.fields.deadline);
        const formattedDeadline = deadlineDate.toLocaleString('en-US', {
            month: 'long',
            day: 'numeric',
            year: 'numeric',
            hour: 'numeric',
            minute: 'numeric',
        });
        const dateAddedDate = new Date(item.fields.date_added);
        const formattedDateAdded = dateAddedDate.toLocaleString('en-US', {
            month: 'long',
            day: 'numeric',
            year: 'numeric',
        });
      const editUrl = `{% url 'main:edit_item' 0 %}`.replace('0', item.pk);
      const deleteUrl = `{% url 'main:delete_item' 0 %}`.replace('0', item.pk);
      htmlString += `
      <div class="card">
        <div class="card-content">
          <h5 class="card-title">Name: ${item.fields.name}</h1> 
          <h5 class="card-title">Page: ${item.fields.amount}</h4>
          <h5 class="card-date">Date Added: ${formattedDateAdded}</h5>
          <h5 class="card-date">Deadline: ${formattedDeadline}</h5>
          <p class="card-description">Description: ${item.fields.description}</p>
          <div class="card-buttons-place">
            <div class="card-buttons">
              <a href="${editUrl}">
                <button type="button" class="btn btn-primary">
                  Edit
                </button>
              </a>
            </div>
            <div class="card-buttons">
              <a href="${deleteUrl}">
                <button type="button" class="btn btn-danger">
                  Delete
                </button>
              </a>
            </div>
          </div>
        </div>
      </div>` 
    })
    return htmlString;
  }
  document.addEventListener("DOMContentLoaded", async function() {
    document.querySelector(".card-box").innerHTML = await refreshItems();
  });
  </script>

{% endblock content %}

main/templates/register.html
{% extends 'base_template.html' %} 

{% block head %}
<title>Register</title>
{% endblock head %} 

{% block content %}

<div class="login">
  <h1>Register</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Daftar" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}